### ISSUE TITLE
[Bug] Missing CRD `customnoderesource`

### ISSUE THREAD

**Issue by Yicheng-Lu-llll** [kubewharf/godel-scheduler#16]
When I attempted to follow the instructions in [dev-quickstart.md](https://github.com/kubewharf/godel-scheduler/blob/main/docs/dev-quickstart.md), I noticed that in the "Generate the required CRDs" step, only three CRDs were generated as shown below:
```shell
ubuntu@ip-172-31-2-249:~$ kubectl get crds
NAME                                       CREATED AT
nmnodes.node.godel.kubewharf.io            2024-01-19T04:34:21Z
podgroups.scheduling.godel.kubewharf.io    2024-01-19T04:34:21Z
schedulers.scheduling.godel.kubewharf.io   2024-01-19T04:34:21Z
```
However, the instructions imply there is another CRD: "customnoderesource." The absence of this CRD will prevent the dispatcher, scheduler and binder from starting, as evidenced by the error message below:
```shell
E0119 04:54:44.126106   79900 reflector.go:138] github.com/kubewharf/katalyst-api/pkg/client/informers/externalversions/factory.go:120: Failed to watch *v1alpha1.CustomNodeResource: failed to list *v1alpha1.CustomNodeResource: the server could not find the requested resource (get customnoderesources.node.katalyst.kubewharf.io)
```

After inspecting,  it appears that there do have only three CRDs defined here: https://github.com/kubewharf/godel-scheduler-api/tree/main/pkg/apis. Perhaps `customnoderesource` should also be uploaded to the [godel-scheduler-api](https://github.com/kubewharf/godel-scheduler-api) repository? I believe it is used to store topology infomation.

**Comment by NickrenREN** [comment]
Hi, @Yicheng-Lu-llll , thanks for sending your issues. 
- `customnoderesource` is defined in `https://github.com/kubewharf/katalyst-api`, it will be used by several repos in kubewharf org, so we don't re-define it in `godel-scheduler-api` repo.
- we ignore this when we wrote the quickstart doc, thanks for pointing it out, we will update our doc soon. 
- btw: this crd is generated and provide in godel scheduler repo too, `https://github.com/kubewharf/godel-scheduler/blob/main/manifests/base/crds/node.katalyst.kubewharf.io_customnoderesources.yaml` , you can apply it directly in order to make the components work

**Comment by NickrenREN** [comment]
@yuey002 please update our quickstart doc when you have time

**Comment by NickrenREN** [comment]
@yuey002 can you help update our quickstart doc when you have time ?

**Comment by Yicheng-Lu-llll** [comment]
I see, Thank you!
